### ISSUE TITLE
browser/curl detection isn't ideal

### ISSUE THREAD

**Issue by michaelgruenewald** [stchris/randoku#23]
The [current code](https://github.com/stchris/randoku/blob/385bed2c41e3176e4f0b48f8c0caf9ee91cf8aea/src/main.rs#L37) detects requests from curl by checking for `curl` in the beginning of the user agent header. This is evidently to show a description page to browsers and return a random number to curl otherwise.

Unfortunately, this shuts out other CLI tools (httpie, etc.) from receiving a random number. [MDN suggests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) that all web browsers have a UA starting with `Mozilla/5.0`, so maybe checking for that would be nicer?

**Comment by stchris** [comment]
Ah nice, that makes more sense! Thanks, I will look into it.
